imdb-binary:
  lr: 0.0002
  data: imdb-binary
  norm: null
  task: gc
  alpha: 0.9
  batch: 64
  debug: 1
  heads: 8  
  epochs: 240
  decoder: gat
  encoder: gat
  pooling: mean
  repeats: 3
  use_cfg: false
  dis_type: gat
  residual: 1
  mask_rate: 0.2
  subgraphs: 640
  activation: relu
  dis_layers: 2
  gen_layers: 2
  hidden_dim: 64  
  replace_rate: 0
  weight_decay: 0.00001
  concat_hidden: false
  dis_attn_drop: 0
  dis_feat_drop: 0
  dis_mask_rate: 0
  dis_optimizer: rmsprop
  gen_attn_drop: 0.3
  gen_feat_drop: 0.1
  gen_optimizer: adam
  num_out_heads: 8
  dis_activation: leakyrelu
  dis_hidden_dim: 1024
  drop_edge_rate: 0
  gen_hidden_dim: 1024
  negative_slope: 0.2
  sample_strategy: rw  
  var_encoder_type: mlp  
  mean_encoder_type: mlp
imdb-multi:
  lr: 0.001
  data: imdb-multi
  norm: null
  task: gc
  alpha: 0.5
  batch: 64  
  heads: 8
  epochs: 50
  decoder: gat
  encoder: gat
  repeats: 3
  dis_type: gat
  residual: 1
  mask_rate: 0.3
  subgraphs: 640
  activation: relu
  dis_layers: 1
  gen_layers: 1
  hidden_dim: 64
  replace_rate: 0
  weight_decay: 0.00001
  concat_hidden: false
  dis_attn_drop: 0
  dis_feat_drop: 0
  dis_mask_rate: 0
  dis_optimizer: rmsprop
  gen_attn_drop: 0.2
  gen_feat_drop: 0.6
  gen_optimizer: adam
  num_out_heads: 8
  dis_activation: leakyrelu
  dis_hidden_dim: 1024
  drop_edge_rate: 0
  gen_hidden_dim: 1024
  negative_slope: 0.2
  sample_strategy: rw
  var_encoder_type: mlp
  mean_encoder_type: mlp
collab:
  lr: 0.0004
  data: collab
  norm: null
  task: gc
  alpha: 0.4
  batch: 64
  debug: 0
  heads: 8  
  device: cuda: 0
  epochs: 80
  decoder: gat
  encoder: gat
  repeats: 2
  dis_type: gat
  residual: 1
  mask_rate: 0.6000000000000001
  subgraphs: 640
  activation: relu
  dis_layers: 1
  gen_layers: 2
  hidden_dim: 64
  model_path: model_save/
  replace_rate: 0
  weight_decay: 0.00001
  concat_hidden: false
  dis_attn_drop: 0
  dis_feat_drop: 0
  dis_mask_rate: 0
  dis_optimizer: rmsprop
  gen_attn_drop: 0.5
  gen_feat_drop: 0.2
  gen_optimizer: adam
  num_out_heads: 8
  dis_activation: leakyrelu
  dis_hidden_dim: 64
  drop_edge_rate: 0
  gen_hidden_dim: 1024
  negative_slope: 0.2
  sample_strategy: rw
  var_encoder_type: mlp
  mean_encoder_type: mlp

